import './js/furniture/furniture-logic.js';
import './js/api.js';
import './js/menu.js';
import './js/order-modal.js';
import './js/product-modal.js';
import './js/faq.js';
import './js/feedback.js';
import './js/feedback-section.js';
import './js/loader.js';
